POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR3aWt5cnlhbkBiYW50dXNha3UuaWQiLCJleHAiOjE3NjQ1OTMzNjAsInVzZXJJZCI6MX0.u7c2ZC7cVSaHm4swFeabCtJ0tE-Lat7_EYooyJrOG2s

{
    "name": "Test event",
    "description": "A test event",
    "location": "A test location",
    "dateTime" : "2025-11-28T13:49:00.000Z"
}