DELETE http://localhost:8080/events/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR3aWt5cnlhbkBlYXNlc2lnbi5pZCIsImV4cCI6MTc2NDU4ODQ4OCwidXNlcklkIjoyfQ.LqOv82UT-yv0IBBd70KqG3I6bFr9oO1zpBNiCRtVJOo